---

- name: Install Fuzzball Substrate
  ansible.builtin.dnf:
    state: present
    name:
      - fuzzball-substrate
      - fuzzball-substrate-orchestrate
    update_cache: true
  register: substrate_install
  until: substrate_install is succeeded
  retries: 3
  delay: 10

- name: Configure Fuzzball Substrate
  ansible.builtin.template:
    src: fuzzball-substrate.env
    dest: /etc/default/fuzzball-substrate.env
  notify: Restart fuzzball-substrate

- name: Get firewalld status
  ansible.builtin.systemd_service:
    name: "firewalld"
  register: firewalld

- name: Add cluster interface to trusted zone
  ansible.builtin.firewalld:
    zone: trusted
    interface: "{{ cluster_interface }}"
    immediate: true
    permanent: false
    state: enabled
  when:
  - firewalld.status.ActiveState == 'active'

- name: Create shared storage mountpoint
  ansible.builtin.file:
    path: /fuzzball/shared
    state: directory
    mode: 0755

- name: Install NFS utilities
  ansible.builtin.package:
    name: nfs-utils
    state: present

- name: Define NFS mount for /fuzzball/shared
  ansible.builtin.template:
    src: systemd/system/fuzzball-shared.mount
    dest: /etc/systemd/system/fuzzball-shared.mount
    mode: 0644
  when: fuzzball_substrate_nfs_mount is defined

- name: Mount /fuzzball/shared
  ansible.builtin.systemd_service:
    name: fuzzball-shared.mount
    state: started
    enabled: true
    daemon_reload: true

- name: Start Fuzzball Substrate
  ansible.builtin.service:
    name: fuzzball-substrate
    state: started
