---

- name: Install metallb
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
    kubeconfig: "{{ kubeconfig }}"
  register: result
  retries: 10
  delay: 10
  until: result.failed is not defined or result.failed == false

- name: Configure metallb pool
  kubernetes.core.k8s:
    state: present
    definition: "{{ metallb_pool_defaults | ansible.builtin.combine(metallb_pool, recursive=true) }}"
    kubeconfig: "{{ kubeconfig }}"
  register: result
  retries: 10
  delay: 10
  until: result.failed is not defined or result.failed == false

- name: Configure metallb advertisement
  kubernetes.core.k8s:
    state: present
    definition: "{{ metallb_advertisement_defaults | ansible.builtin.combine(metallb_advertisement, recursive=true) }}"
    kubeconfig: "{{ kubeconfig }}"
